# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRKQyZRH03SJhyoB2TYJEKOjOPveO9G3

3. Deployment dan Menjalankan Streamlit
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # 1. Konfigurasi Halaman
# st.set_page_config(page_title="Dashboard Analisis Pelanggan", layout="wide")
# 
# # 2. Fungsi Load Data
# @st.cache_data
# def load_data():
#     df = pd.read_csv('rfm_result.csv')
#     return df
# 
# try:
#     df_rfm = load_data()
# 
#     # SIDEBAR: AREA INTERAKSI USER
#     st.sidebar.header("⚙️ Filter Interaktif")
# 
#     # Input 1: Pencarian ID Pelanggan
#     search_id = st.sidebar.text_input("Cari Customer ID:", "")
# 
#     # Input 2: Filter berdasarkan Cluster (Multiselect)
#     available_clusters = sorted(df_rfm['Cluster'].unique())
#     selected_clusters = st.sidebar.multiselect(
#         "Pilih Segmen/Cluster:",
#         options=available_clusters,
#         default=available_clusters
#     )
# 
#     # Input 3: Slider untuk Rentang Nilai Monetary (Belanja)
#     min_monetary = int(df_rfm['Monetary'].min())
#     max_monetary = int(df_rfm['Monetary'].max())
#     selected_monetary = st.sidebar.slider(
#         "Rentang Total Belanja (Monetary):",
#         min_monetary, max_monetary, (min_monetary, max_monetary)
#     )
# 
#     # LOGIKA FILTERING
#     mask = (df_rfm['Cluster'].isin(selected_clusters)) & \
#            (df_rfm['Monetary'].between(selected_monetary[0], selected_monetary[1]))
# 
#     if search_id:
#         mask = mask & (df_rfm['customer_unique_id'].str.contains(search_id))
# 
#     df_filtered = df_rfm[mask]
# 
#     # MAIN PANEL: TAMPILAN DASHBOARD
#     st.title("📊 Dashboard Segmentasi Pelanggan (Olist)")
#     st.markdown(f"Menampilkan **{len(df_filtered)}** pelanggan berdasarkan filter Anda.")
# 
#     # Baris 1: Ringkasan Metric
#     col1, col2, col3 = st.columns(3)
#     col1.metric("Rerata Recency", f"{int(df_filtered['Recency'].mean())} Hari")
#     col2.metric("Rerata Frequency", f"{df_filtered['Frequency'].mean():.2f} Order")
#     col3.metric("Total Revenue", f"R$ {df_filtered['Monetary'].sum():,.2f}")
# 
#     # Baris 2: Grafik Interaktif
#     st.subheader("Visualisasi Hubungan Recency vs Monetary")
#     fig = px.scatter(
#         df_filtered,
#         x="Recency",
#         y="Monetary",
#         color="Cluster",
#         size="Frequency",
#         hover_name="customer_unique_id",
#         color_continuous_scale=px.colors.sequential.Viridis,
#         title="Peta Sebaran Pelanggan (Gunakan kursor untuk zoom/detail)"
#     )
#     st.plotly_chart(fig, use_container_width=True)
# 
#     # Baris 3: Detail Data
#     with st.expander("Klik untuk melihat detail data tabel"):
#         st.write(df_filtered.head(100))
# 
# except FileNotFoundError:
#     st.error("File 'rfm_result.csv' tidak ditemukan. Pastikan proses analisis data sudah dijalankan!")

!pip install -q streamlit pyngrok

from pyngrok import ngrok
!ngrok config add-authtoken 37R5NqAJZTj4LBoBtWXClJKIA1I_2CGfnXVqWDJzPFNgEpd2f

# Jalankan Streamlit di background
import subprocess
!pkill streamlit
subprocess.Popen(['streamlit', 'run', 'app.py', '--server.port', '8501'])

# Buka Tunnel Ngrok
publ_url = ngrok.connect(8501)
print(f"Dashboard Anda aktif di: {publ_url}")